### ISSUE TITLE
bundle can't find 'minima'

### ISSUE THREAD

**Issue by jeremiah** [Pelagicore/pelux.io#16]
sylph.jeremiahfoster.com:~/GitHub/jeremiah/pelux.io> bundle exec jekyll serve
/var/lib/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/drops/document_drop.rb:8: warning: already initialized constant Jekyll::Drops::DocumentDrop::NESTED_OBJECT_FIELD_BLACKLIST
/usr/lib/ruby/vendor_ruby/jekyll/drops/document_drop.rb:8: warning: previous definition of NESTED_OBJECT_FIELD_BLACKLIST was here
/var/lib/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/drops/drop.rb:8: warning: already initialized constant Jekyll::Drops::Drop::NON_CONTENT_METHODS
/usr/lib/ruby/vendor_ruby/jekyll/drops/drop.rb:8: warning: previous definition of NON_CONTENT_METHODS was here
Configuration file: /home/jeremiah/GitHub/jeremiah/pelux.io/_config.yml
Configuration file: /home/jeremiah/GitHub/jeremiah/pelux.io/_config.yml
Source: /home/jeremiah/GitHub/jeremiah/pelux.io
Destination: /home/jeremiah/GitHub/jeremiah/pelux.io/_site
Incremental build: disabled. Enable with --incremental
Generating... 
Build Warning: Layout 'post' requested in _posts/2017-05-15-Why-use-GENIVIs-NSM-in-PELUX.md does not exist.
Build Warning: Layout 'post' requested in _posts/2017-05-29-How-to-get-journald-in-DLT.md does not exist.
Build Warning: Layout 'post' requested in _posts/2017-06-07-Why-GENIVI-DLT-as-logging-aggregator.md does not exist.
Build Warning: Layout 'page' requested in components.md does not exist.
Build Warning: Layout 'page' requested in demo.md does not exist.
Build Warning: Layout 'page' requested in documentation.md does not exist.
Build Warning: Layout 'page' requested in download.md does not exist.
Build Warning: Layout 'page' requested in get-involved.md does not exist.
Conversion error: Jekyll::Converters::Scss encountered an error while converting '/assets/main.scss':
File to import not found or unreadable: minima. on line 1
jekyll 3.1.6 | Error: File to import not found or unreadable: minima. on line 1

**Comment by rpannek** [comment]
Interesting, did you run `bundle install` after checking out?

**Comment by jeremiah** [comment]
Installing 'minima' as a gem cleared this problem.
Fix: `gem install minima`

**Comment by rpannek** [comment]
Hm but then we should add this gem to the Gemfile, one shouldn't need to install it manually. Did you run `bundle install` which should have installed all such dependencies?

**Comment by jeremiah** [comment]
Yeah, I ran `bundle install`, but I didn't have the 'bundle' binary. That is obviously installed at GitHub but I doubt it is a standard part of a Linux distro.

**Comment by rpannek** [comment]
Ok, then I guess the flow should be like this:

    sudo apt install ruby gem
    gem install bundle
    git clone ...
    cd pelux.io
    bundle install
    bundle exec ...

**Comment by jeremiah** [comment]
Wouldn't it be 'gem install bundler'?

**Comment by rpannek** [comment]
Ah yeah, typo, you're right.
