### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by jeremiah** [Pelagicore/pelux.io#18]
[2017-06-20 13:43:45] ERROR `/favicon.ico' not found.

**Comment by tobsan** [comment]
Could you give some more details? It would be nice to have a favicon, and I'm not seeing one in the artifacts for the site build. Should we add one? Or should we tell Jekyll that we don't have one?

**Comment by jeremiah** [comment]
I think we should have one. We can use this: http://www.pelagicore.com/favicon.png?v=2 That URL can be stuffed into the HTML source somewhere in the header; 
`<link rel="shortcut icon" type="image/png" href="favicon.ico"/>`
 We'd have to rename the file from favicon.png to favicon.ico if we want to reuse the html above and we'd have to put it in a place that the browser can find it so the href path will have to be right, but that is kinda easy to do.

**Comment by jeremiah** [comment]
Shall I send a PR? Or are you already in jekyll making magic?

**Comment by tobsan** [comment]
I'm not planning anything, no. Please send a PR!
