### ISSUE TITLE
License information in generated docs?

### ISSUE THREAD

**Issue by gunnarx** [Pelagicore/pelux.io#49]
The generated docs only state © Copyright Pelagicore AB whereas the source code license is CC-BY-SA according to the README.  It's not wrong, but could be made more complete.  Have you already decided, if maybe you want to provide the license on the generated content also?

**Comment by rpannek** [comment]
I wonder if there needs to be a special license on the generated content, wouldn't it just automatically inherit the license from the source code like a binary?

**Comment by gunnarx** [comment]
I would agree that it does since the text is the same.  I just mean that users consume the web pages, they don't consume the source code.  So it would be clearer to have the license stated on the resulting  web pages also.  Copyright + license is clearer than just Copyright, which could suggest to a reader they are not given any license to reuse the information in the way that the real license actually allows.

**Comment by rpannek** [comment]
Ah yeah, you're right, I'll try to ping someone about it.

**Comment by jeremiah** [comment]
Shouldn't this issue go here: https://github.com/Pelagicore/software-factory/issues ?

**Comment by gunnarx** [comment]
> Shouldn't this issue go here: https://github.com/Pelagicore/software-factory/issues ?

Maybe, or maybe the change needs to be applied in more than one place.   I'll let you, @rpannek and @Pelagicore sort that out.  Feel free to move the issue if needed. I think you normally work with assigning issues - so who should be assigned?

**Comment by rpannek** [comment]
I guess the PELUX maintainers should make it happen, ping: @tobsan and @thenor

**Comment by tobsan** [comment]
I suppose such info should go into the footers of pelux.io pages as well as in the software-factory. I'll see what I can do :)
